const productsData = [
    {
      id: 1,
      name: "Black T-shirt",
      img: "../img/1.jfif",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo officiis labore vel, ",
      price: "10",
    },
    {
      id: 2,
      name: "Gray T-shirt",
      img: "../img/2.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo officiis labore vel, ",
      price: "20",
    },
    {
      id: 3,
      name: "Blue T-shirt",
      img: "../img/3.jpg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo officiis labore vel, ",
      price: "30",
    },
    {
      id: 4,
      name: "Sleeve T-shirt",
      img: "../img/4.jfif",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo officiis labore vel, ",
      price: "40",
    },
    {
      id: 5,
      name: "Camera",
      img: "../img/c1.jpg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo officiis labore vel, ",
      price: "120",
    },
    {
      id: 6,
      name: "Camera2",
      img: "../img/c2.jpg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo officiis labore vel, ",
      price: "200",
    },
    {
      id: 7,
      name: "Camera3",
      img: "../img/c3.jpg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo officiis labore vel, ",
      price: "210",
    },
    {
      id: 8,
      name: "Camera4",
      img: "../img/c4.jpg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo officiis labore vel, ",
      price: "220",
    },
    {
      id: 9,
      name: "Camera4",
      img: "../img/c5.jpg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo officiis labore vel, ",
      price: "230",
    },
  ];